### ISSUE TITLE
For newer versions of .NET use nameof for argument names

### ISSUE THREAD

**Issue by OldrichDlouhy** [MicrosoftDocs/visualstudio-docs.cs-cz#11]
For new versions of .NET, the better practice is to use nameof(parameter) instead of "parameter" to ensure parameter name stays correct in case of refactoring.

Example:
throw new ArgumentException(nameof(person));

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: a80979f5-bdc4-f5c8-9adf-fea83bafaa7e
* Version Independent ID: a28c47de-cf33-0aff-cff2-e3da9c709623
* Content: [CA1062: Ověřte argumenty veřejných metod - Visual Studio](https://docs.microsoft.com/cs-cz/visualstudio/code-quality/ca1062-validate-arguments-of-public-methods?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca1062-validate-arguments-of-public-methods.md](https://github.com/MicrosoftDocs/visualstudio-docs.cs-cz/blob/live/docs/code-quality/ca1062-validate-arguments-of-public-methods.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by srvbpigh** [comment]
Hello, @OldrichDlouhy
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @OldrichDlouhy 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/visualstudio-docs/issues/4110

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
