### ISSUE TITLE
ProjectFilesGenerator.ProjectFileGeneration name

### ISSUE THREAD

**Issue by xmedeko** [MicrosoftDocs/visualstudio-docs.cs-cz#6]
Please, document how `name` in the `ProjectFilesGenerator.ProjectFileGeneration` looks like - is that the project name, csproj file name or csproj full path? 

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: 70a4fd25-8def-13c4-d35f-e81043b21e4d
* Version Independent ID: 55ceba14-64a8-20a9-73ce-e16f410f1936
* Content: [Přizpůsobení souborů projektu vytvořených nástrojem VSTU - Visual Studio](https://docs.microsoft.com/cs-cz/visualstudio/cross-platform/customize-project-files-created-by-vstu?view=vs-2017)
* Content Source: [docs/cross-platform/customize-project-files-created-by-vstu.md](https://github.com/MicrosoftDocs/visualstudio-docs.cs-cz/blob/live/docs/cross-platform/customize-project-files-created-by-vstu.md)
* Product: **visual-studio-windows**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by CeciAc** [comment]
Hello, @xmedeko 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/visualstudio-docs/issues/2899

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
